---
title: "Intro to Group Projects"
date: "`r Sys.Date()`"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library("jpeg")
library("tidyverse")
```

## Meet your group
Please take 10 minutes to meet your partner(s) for the class project. Here is what you need to do:  
1. Introduce yourself and exchange contact information.  
2. Think about the kind of data and questions you would like to pursue.  
3. Please make sure that you sit next to your group members for the rest of the quarter.  

## Grading & Expectations
1. 90 points (30%) of your course grade.  
2. 3-4 students per group.  
3. "Wild" data, no built-in or previously curated data.  
4. Each student must contribute; you evaluate each other at the end of the quarter.  
5. You must include a Shiny app.  
6. Unless told otherwise, you must include a presentation.  

## Guidelines & Suggestions
1. Find multiple candidate datasets; pick the best one as a group.  
2. The data should be big, but not too big, and have a story to tell.  
3. You should have a mix of continuous and categorical variables.  
4. The data should come from a trusted source.  
5. It's OK to make it fun.  

## For today
1. Work together to browse online and find some candidate data.  
2. Can they be used to show the range of skills you have learned?  
3. Can they be used to tell a story? Nobody wants to see 10 scatterplots!  
4. Leave with a plan to assemble 3-5 candidate datasets by Tuesday.  