---
title: "Lab 1: Getting Started, Part 1"
author: "Joel Ledford"
date: "Winter 2019"
output:
  html_document:
    theme: spacelab
    toc: yes
    toc_float: yes
---

## Background
In nearly every field of science, our ability to generate data has exceeded our capacity for analysis. For me, this means that there is the potential for loss to science; many important discoveries may go unnoticed because we are unable to efficiently analyze data.

There is also a growing problem of curation. As the analyses and data become more complex, research labs have a problem of storing and managing data such that it can be used in future analyses or shared with colleagues. As students, postdocs, and visiting scientists come and go in labs, there is often a mess left behind where data are inefficiently stored and analytical scripts are hard to interpret.

Lastly, with the widespread availability of data online there is the potential for new scientific discovery or insight through exploratory data analysis. In many cases a clean, organized workflow will yield new perspectives and promising results.  

## Objectives
The goal for this course is to help get you started learning to manage, transform, and visualize data using the R programming language. You will learn to clearly and neatly organize messy data, transform it in ways that address your questions, and communicate results in a variety of formats. The course is designed for people with **no prior programming experience**. My only caveat is that there is a substantial learning curve but, working together, we should be able to make learning R easier, interesting, and fun.

Why spend the time? If you are pursuing any research path in science, this class will give you a significant competitive advantage and save you countless hours as most people struggle to [learn R on their own](https://www.wired.com/2017/03/biologists-teaching-code-survive/). Even if you are not pursuing a research career, companies routinely hire data scientists (or people with skills in data science) to anlyze a variety of data.

## Resources
Given the open source nature of R, many resources are available online. We will use a combination of resources in the class, but key items are listed below.

- [R for data science](https://r4ds.had.co.nz/)
- [R cheatsheets](https://www.rstudio.com/resources/cheatsheets/)
- [RStudio keyboard shortcuts](https://support.rstudio.com/hc/en-us/articles/200711853-Keyboard-Shortcuts)

## Data Science at UC Davis
Our campus has a wealth of expertise in data science, from working groups to full initiatives. Should your interests progress, here are some links. They offer regular workshops and maintain archives.

- [Data Science Initiative, UC Davis](http://dsi.ucdavis.edu/)  
- [Davis R Users Group](http://d-rug.github.io/) 

## Lab 1
The first goal of lab 1 is to get everyone started using R, Rstudio, and Git. All of our work will be done in RStudio and uploaded to the class GitHub repository. We will use RMarkdown to write all of our code; it allows us to easily check functionality and neatly annotate chunks.

At the start of each lab session, I will randomly pull someone's code from the GitHub repository and use it as an example. There are many, many ways to solve the same problems in R and seeing other people's code is a great way to learn. This is not about shaming people who make mistakes!  

This first lab is tedious, so please be patient. It is important that everyone is set-up correctly before they leave today. In the spirit of the R universe, our class is a community. If you see someone struggling, please give them some help.  

## Setup your own computer
You are welcome to use your own computer, but in order to do so you need to install R, RStudio, and Git. If you would like to set-up your own computer, please follow the directions [here](https://jmledford3115.github.io/datascibiol/setup.html).

## Create a GitHub account
[**GitHub**](www.github.com) is a repository for programmers. Programmers upload code and make it publicly available. **Git** is software that is used for version control. It tracks changes and is especially helpful when multiple people are collaborating on a project; if a mistake is made it can be easily tracked back and retrieved. Both can be integrated with RStudio.  

Since we will use GitHub as a repository for all assignments, we need to make an account for each student and build a new project through RStudio to set-up Git.  

Navigate to www.github.com and create a free account. [Email](mailto:jmledford@ucdavis.edu) your username to me. You will receive an email to join the repository for our course.  

## Open RStudio
Once you are in RStudio, open a new markdown document: **File>New File>R Markdown**  

In this new file insert a new R code chunk by clicking on the green `insert` tab and selecting R. The mac shortcut is option + command + i. The PC shortcut is Ctrl + Alt + i.

## Install the tidyverse
One strength of R is that there are thousands of add-on packages that perform specialized functions. The packages are referred to as libraries.  

In this class, we will routinely use the library called the **tidyverse**. Libraries need to be installed in order to work, and whenever you update R you also need to update all of the packages that you use.
```{r eval=FALSE, include=TRUE}
install.packages("tidyverse")
install.packages("nycflights13")
```

## Create a new project with Git
Once you have created a GitHub account, we need to practice. I have made a repository for our class titled: FRS417-DataScienceBiologists. You should be able to login to GitHub and find this organization. You should see a directory associated with your login name.  

Click on your directory to enter. Once there, click on the green button in the top right corner titled **Clone or download**. A URL will appear and you should copy that address.

+ In RStudio, navigate to File> New Project.

+ From the **Create Project** window, select Version Control> Git.

+ Paste the URL that you copied from GitHub into the directory. 

## Perform a commit (local), and push files to GitHub (remote)
Navigate to the [dummy_push](https://jmledford3115.github.io/datascibiol/dummy_push.html) file. Copy and paste all of the code chunks in this file into a new RMarkdown file called `dummy_push_login`. Replace `login` with your GitHub login name.  

In the top right window of RStudio, you should see several options as tabs including **Environment, History, Connections, and Git**. Click on the `Git` tab.

Make sure you are in the correct working directory and save your work. Now, click on the **Commit** tab.

Enter a note to keep track of each commit that you make. In the left window, make sure the file that you have changed is selected. Now, click the **Commit** button on the right window.

Lastly, we need to upload our changes to GitHub. This is called a **Push**. When you are ready, click the push button and your files will be uploaded. Wait a few moments and then check your directory on GitHub to see that it worked.

## Git and GitHub Issues
We will encounter many issues over the next few weeks with Git and GitHub. These will be caused mostly by user error, but sometimes weird things happen. If you are stuck, especially in the first few sessions, stop trying to commit, push, or pull. Get my attention and we will sort things out.

That's it, let's take a break!