---
title: "Lab 2 Homework"
author: "Joel Ledford"
date: "Winter 2019"
output:
  html_document:
    theme: spacelab
    toc: no
---

## Instructions
Answer the following questions and complete the exercises in RMarkdown. Please embed all of your code, keep track of your versions using git, and push your final work to our [GitHub repository](https://github.com/FRS417-DataScienceBiologists). I will randomly select a few examples of student work at the start of each session to use as examples so be sure that your code is working to the best of your ability.

## Load the tidyverse
```{r}
library("tidyverse")
```

## Mammals Sleep
For this assignment, we are going to use built-in data on mammal sleep patterns.  

1. From which publication are these data taken from? Don't do an internet search; show the code that you would use to find out in R.



2. Provide some summary information about the data to get you started; feel free to use the functions that you find most helpful.



3. Make a new data frame focused on body weight, but be sure to indicate the common name and genus of each mammal. Sort the data in descending order by body weight.



4. We are interested in two groups; small and large mammals. Let's define small as less than or equal to 1kg body weight and large as greater than or equal to 200kg body weight. For our study, we are interested in body weight and sleep total Make two new objects (large and small) based on these parameters. Sort the data in descending order by body weight.





5. Let's try to figure out if large mammals sleep, on average, longer than small mammals. What is the average sleep duration for large mammals as we have defined them?



6. What is the average sleep duration for small mammals as we have defined them?



7. Make two new variables in the msleep data frame: 1. the proportion of rem sleep, and 2. body weight in grams.



8. What are the top five mammals with the greatest proportion of rem sleep? Include their body weights for comparison.



9. Which animals sleep at least 18 hours per day? Be sure to show the name, genus, order, and sleep total. Sort by order and sleep total.



## Push your final code to [GitHub](https://github.com/FRS417-DataScienceBiologists)
Make sure that you push your code into the appropriate folder. Also, be sure that you have check the `keep md` file in the knit preferences.