---
title: "BIS 015 Syllabus"
author: "Joel Ledford"
date: "Winter 2020"
output:
  html_document:
    theme: spacelab
    toc: yes
    toc_float: yes
  word_document:
    toc: yes
---    

## Class Times and Contact Information  
+ Fridays, 2:10-4:00p, 2102 SCC  
+ [Joel Ledford](mailto:jmledford@ucdavis.edu)  
+ Office: 2220 Life Sciences, Department of Plant Biology  

## Teaching Assistant  
+ [Rebecca Godwin](mailto:rgodwin@ucdavis.edu)  

## Office Hours    
Office hours are by appointment. Please send us an email and we will setup a time to meet.  

> **Want to Make it as a Biologist? Better Learn to Code**  
> "In biology, big data is the thing. Every day, biologists go into the lab to coax data out of living matter—more and more data, with the advent of biological tools like Crispr/Cas9..."We cannot manually look through 15,000 data points anymore," Udeshi says. To analyze it all, biologists need to write programs specifically tailored for their experiments."  
> [Wired Magazine (2017)](https://www.wired.com/2017/03/biologists-teaching-code-survive/)

## Course Summary  
In BIS 015, you will be introduced to the fundamentals of data science with emphasis on data frequently used by biologists. We will use the R software environment to develop and practice key skills including data management, transformation, analysis, and visualization. Examples will span a range of disciplines including social science, ecology, evolution, and genetics. Labs will use a problem-solving approach where students build on previously learned skills culminating in a small, group-based project. 

This class is designed for students with *no background in computer programming, R, or statistics*. My assumption is that you know how to turn a computer on and use a mouse- that's it!  

## Course Structure  
Each lab will include a combination of worked examples and group practice. Because the labs are two hours, we will divide each session into two parts. Each lab has an associated homework assignment to practice skills. If we finish early, we will spend the remainder of our time working on the homework together.  

## Equipment  
Please use the lab computers while working in lab. This makes things far easier to troubleshoot. You will need access to a computer running the latest versions of R and RStudio in order to complete the homework.    

## Grading  
Grading is divided into four parts:  

1. **Weekly homework assignments (60%)**. Each assignment must be completed and uploaded to GitHub prior to the next lab. I will randomly pull an example from GitHub to discuss with the class to see alternate solutions and address issues. You must complete all homework assignments to receive a passing grade in the course.  

2. **Midterm (10%)**. The midterm will help us keep one another accountable. The exam will likely be take-home, depending on our progress.  

3. **Class project (30%)**. As part of the class, you will form a group to explore a project in data science. The project may be based on any available data of interest to the group, and should highlight skills learned in the labs. The group will present their results during the last lab session.  

4. **Attendance**. Attendance is mandatory. Students are only allowed one absence during the quarter. Please [email me](mailto:jmledford@ucdavis.edu) if you need to miss a lab.  

## Reading  
[R for Data Science](https://r4ds.had.co.nz/), Grolemund and Wickham (2017).  

## Course Learning Goals  
*At the end of this course, you will be able to:*  

1. Use R and RStudio to perform basic analyses including arithmetic and basic statistics.  
2. Work with multiple types of data in R and RStudio including vectors, data frames, and nucleotide sequences.  
3. Import and transform complex, messy data for analysis in R using `dplyr`, `tidyr`, and `purrr`.  
4. Produce a variety of plots and charts to visualize results of data analysis using `ggplot2`.  
5. Build an exploratory analysis pipeline that can be applied to a variety of data types and structures.  
6. Use Shiny to build an interactive application.  
7. Use geospacial data to produce distribution maps.  

## Office Hours  
Office hours are by appointment. If there are problems with the assignments, it is important that we communicate together as a class. Please use the class email list as a first step so we all may benefit.  

## About Me  
I am an assistant teaching professor in the department of [Plant Biology](http://www-plb.ucdavis.edu/). My research is focused on education and spider biology. My experience in R has mostly involved statistical analysis in education and phylogenetics. I also teach part of the introductory biology series `BIS2C` (Fall and Winter) and introductory plant biology `PLB10` (Spring).  

## Do's and Dont's  
Learning any programming language is hard; it only gets easier with time and practice. Don't give up!  

+ Please *do* ask questions, get help from class partners, and complete assignments on-time.  
+ Please *don't* miss class or get behind on the homework.  

I am very open to suggestions, especially when it comes to relevant and interesting examples. If you find data that are especially interesting to you please let me know and I will do my best to incorporate it into class examples. Most of all, have fun learning R and if you are not then let me know!  

-->[Home](https://jmledford3115.github.io/datascibiol/)