---
title: "Lab 10 Intro"
date: "`r Sys.Date()`"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library("jpeg")
```

## Group project  
As you meet in groups today and think about the kind of data and project you want to pursue, consider these suggestions.  
1. You are free to use whatever data you want, but it should be reasonably sized and not too messy.  
2. It should have a mix of categorical and continuous variables.  
3. Know your audience- don't be too hip for the room.  
4. Be polite and listen to each other, please.  

## Meet your group
Please take 10 minutes to meet your partner(s) for the class project. Here is what you need to do:  
1. Introduce yourself and exchange contact information.  
2. Think about the kind of data and questions you would like to pursue.  
3. Browse around on the internet a little to see what is available- are your questions reasonable?    
4. Make a plan to collect at least two different sources of data to share on Thursday.  

## Seating & Set-up
1. Please make sure that you sit next to your group members for the rest of the quarter.
2. Please set-up your computer as normal.

## Warm-up
1. Please load the homerange data `Tamburelloetal_HomeRangeDatabase.csv`
2. Show the min, mean, and max log10.mass by taxonomic class in the dataset.
3. Make a plot that best summarizes this output.