---
title: "Setup Instructions"
date: "`r Sys.Date()`"
output:
  html_document:
    theme: spacelab
    toc: yes
    toc_float: yes
---

## Lab Computers  
This quarter we are fortunate to be able to use the computers in the SCC. Each of these computers is up-to-date, and the installed software is exactly the same. This makes following my instructions much easier, but you will likely want to have the ability to work at home. Please follow the directions below to set-up your personal computer.  

## Setup  
Before we get started this quarter, it is very important that you spend time making sure that your computer is set-up and ready to go. The first step in this is just basic maintenance; i.e. clean up your desktop and update your OS. Having lots of files on your desktop can negatively impact your computer's performance. Data scientists are neat and tidy! Spend time getting yourself organized.  

In order to get set-up, you need to do four things:  

+ [R](https://www.r-project.org/)  
+ [RStudio](https://www.rstudio.com/)  
+ [GitHub Desktop](https://desktop.github.com/)

### 1. Download the most recent version of R and install
R is open source and constantly changing. Make regular version checks part of your routine. R will run on a variety of platforms, but there are slight differences between Mac and PC versions.  

Download the latest version of R [here](https://ftp.osuosl.org/pub/cran/) and install.  

### 2. Download the most recent version of RStudio and install
RStudio is a [GUI](https://www.computerhope.com/jargon/g/gui.htm) that allows for more intuitive operation of R and includes numerous additional functions. All of our work will be done in RStudio.  

Download the latest version of RStudio [here](https://www.rstudio.com/) and install.  

### 3. Download the most recent version of GitHub Desktop and install  
GitHub is the website where we will upload all of our work, including homework and class files. [GitHub Desktop](https://desktop.github.com/) is a [GUI](https://www.computerhope.com/jargon/g/gui.htm) interface that allows us to keep track of changes (version control) and upload.  

### 4. GitHub Account
You need to make a personal account on GitHub. Navigate to [GitHub](http://www.github.com) and create a free account.  

-->[Home](https://jmledford3115.github.io/datascibiol/)  