---
title: "Lab 1 Homework"
author: "Type Your Name Here"
date: "`r Sys.Date()`"
output:
  html_document: 
    theme: spacelab
    keep_md: yes
---

## Instructions
Answer the following questions and/or complete the exercises in RMarkdown. Please embed all of your code and push the final work to your repository. Your report should be organized, clean, and run free from errors. Remember, you must remove the `#` for any included code chunks to run.  

**1. Please join the [class discord](https://forms.gle/AHHXd3aobaAdkkFg9). Put your screen name below.** 

**2. Please tell us why you are taking BIS 15L.**

**3. Do you have any coding experience? If yes, please tell us what languages you have coded in and your level of experience.**

**4. Navigate to my repository on GitHub. Notice that near the bottom there is a description of the repository. You want something like this on your repository! It is built by making edits to the `README.md` file using RMarkdown. Edit your repository's `README.md` file so that you have an informative description, including your email address. Be creative! You don't need to just copy mine. There are lots of examples online.**  

**5. Make sure that you have completed `dummy_push.Rmd`. This includes successful upload to your repository. Put the link to your repository below so we can check.**

## Knit and Upload
Please knit your work as a .pdf or .html file and upload to Canvas. Homework is due before the start of the next lab. No late work is accepted. Make sure to use the formatting conventions of RMarkdown to make your report neat and clean!  