---
title: "Lab 1 Intro"
date: "`r Sys.Date()`"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library("jpeg")
```

## Welcome!
1. If you are registered, please find a seat.  
2. Take a moment to check out the class Canvas page.  
3. Take a moment to check out the class webpage.  
4. Have you joined the class Discord?  

## Syllabus (brief)
1. Introductions  
2. Equipment
3. Homework, midterms, class project  
4. Attendance
5. Waitlist

## Meet Your Classmates
### *With a partner, discuss the following questions*
1. Why are you taking BIS 15L?  
2. Do you have an prior coding experience?  
3. How do you think BIS 15L will help you in your major?  

## Computer Hygiene
1. Make sure all of the latest updates are installed for your OS.  
2. Organize your desktop.  
3. Close all open tabs on your browser.  
4. Completely shut down and restart your computer.  
5. Wipe down the keyboard and clean your screen.  
6. Commit to keeping your computer happy and healthy this quarter.  