---
title: "Lab 12 Intro"
date: "`r Sys.Date()`"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library("jpeg")
```

## Seating & Set-up
1. Please make sure that you sit next to your group members for the rest of the quarter.
2. Please set-up your computer as normal.

## Homework
1. Homework 11 is challenging and similar to your midterm.  
2. Take a few minutes to compare your answers with a neighbor.  

## Group project  
1. As part of your group project, please make a new GitHub repository and add your group members as collaborators.  
2. Please make sure that you have a README file in your repository that explains what your project is about.  
3. Your repository needs a specific name: BIS15W2025_groupX, where X is your group number.  
4. Please make the repository public, so your classmates can see your work.  
5. We will go around and check everyone's data today, so be ready to show us what you have.  
6. If you get this all done early, please start trying to work on your project.  