---
title: "Lab 5 Intro"
date: "`r Sys.Date()`"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library("jpeg")
```

## Setup
1. Go to iclicker.com and record your attendance.
2. Login to the lab computer (please don't use your personal computer).  
3. Navigate to github.com and login.  
4. Find the class repository "datascibiol" (https://github.com/jmledford3115/datascibiol).  
5. Download a copy the class repository to the desktop.  
6. Clone your repository to the desktop.  
7. Copy the files for today's lab from the class repository and paste them into **your** repository.  
8. Open today's lab in RStudio.  

## Agenda
1. Review `select()` and `filter()`.  
2. Learn how to use `filter()` on multiple conditions.  
3. Finish and push homework #4.  
4. Move on to lab #5.  

## Review from last time
### *With a partner, discuss the following questions*
1. What is the association between the tidyverse, dplyr, select, and filter?  
2. Describe how `select ()` can be used to transform data frames.  
3. Describe how `filter ()` can be used to transform data frames. 

## Warm-up
The warm-up will use the fish data from lab 4. These data are from: Gaeta J., G. Sass, S. Carpenter. 2012. Biocomplexity at North Temperate Lakes LTER: Coordinated Field Studies: Large Mouth Bass Growth 2006. Environmental Data Initiative.  [link](https://portal.edirepository.org/nis/mapbrowse?scope=knb-lter-ntl&identifier=267). 

You will need the tidyverse to complete the warm-up- be sure to load the library.  

1. Load the fish data. 

2. Transform the fish data to only include the variables lakeid and length.  Store this as a new dataframe called "fishlength".   

3. Filter the `fish` data to include the samples from lake "BO".  

4. Calculate the mean length of fish from lake "BO".  